apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app }}-nginx-config
data:
  prod.conf: |-
    server {
        listen 4443;
        root /var/www/html;
        index index.php index.html index.htm;
        server_tokens off;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_index index.php;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        try_files $uri $uri/ =404;
        error_page 404 =302 https://tw.yahoo.com/?err=404&err_url=$scheme://$host$request_uri;
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
            return 405;
        }
        
        location ~* /\. {
            deny all;
        }

        location ~* ^/(status|ping)$ {
            allow 202.89.121.0/24;
            allow 203.83.217.0/24;
            allow 10.0.0.0/8;
            allow 172.31.0.0/24;
            allow 192.168.0.0/16;
            allow 127.0.0.1;
            deny all;
            fastcgi_pass 127.0.0.1:9000;
        }

        location /nginx_status {
            allow 202.89.121.0/24;
            allow 203.83.217.0/24;
            allow 10.0.0.0/8;
            allow 172.31.0.0/24;
            allow 192.168.0.0/16;
            allow 127.0.0.1;
            deny all;
            stub_status on;
        }

        location / {

        }

        location ~* \.(jpg|jpeg|gif|png|ico)$ {
            expires 30m;
            add_header Cache-Control "public";
        }

        location ~* \.(css|js)$ {
            expires 10m;
            add_header Cache-Control "public";
        }

        location ~* \.php$ {
            fastcgi_pass 127.0.0.1:9000;
        }
    }

  staging.conf: |-
    server {
        listen 4443;
        root /var/www/html;
        index index.php index.html index.htm;
        server_tokens off;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param HTTP_PROXY "";
        fastcgi_index index.php;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
        try_files $uri $uri/ =404;
        error_page 404 =302 https://tw.yahoo.com/?err=404&err_url=$scheme://$host$request_uri;
        if ($request_method !~ ^(GET|HEAD|POST)$ ) {
            return 405;
        }

        location ~* /\. {
            deny all;
        }

        location / {

        }

        location ~* \.(jpg|jpeg|gif|png|ico)$ {
            expires 30m;
            add_header Cache-Control "public";
        }

        location ~* \.(css|js)$ {
            expires 10m;
            add_header Cache-Control "public";
        }

        location ~* \.php$ {
            fastcgi_pass 127.0.0.1:9000;
        }
    }
