apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-service
  labels:
    partner: {{ .Values.partner }}
    app: {{ .Values.app }}
    env: {{ .Values.labels.env }}
    component: app
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.port }}
      {{- if $port.nodePort }}
      nodePort: {{ $port.nodePort }}
      {{- end }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}
  selector:
    app: {{ .Values.app }}
    component: app
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app }}-fpm-metrics
  labels:
    partner: {{ .Values.partner }}
    app: {{ .Values.app }}
    env: {{ .Values.labels.env }}
    component: app
    metrcs: fpm
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9253
  selector:
    app: {{ .Values.app }}
    component: app