partner: yahoo
app: demo
imageTag: latest
labels:
  env: staging

appImage:
  repository: 049299585218.dkr.ecr.ap-northeast-1.amazonaws.com/partner-yahoo-demo/fe
  tag: latest
  config:
    name: fe-php
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi

nginxImage:
  repository: 049299585218.dkr.ecr.ap-northeast-1.amazonaws.com/partner-yahoo-demo/nginx
  tag: latest
  config:
    imagePullPolicy: IfNotPresent
    name: fe-nginx
    terminationMessagePolicy: FallbackToLogsOnError
    ports:
      - containerPort: 4443
        name: fe-nginx
    resources:
      requests:
        cpu: 50m
        memory: 500Mi
      limits:
        cpu: 500m
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      runAsUser: 101
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/staging.conf
        subPath: staging.conf

volumes:
  - name: config
    configMap:
      name: demo-nginx-config
  # - name: env
  #   secret:
  #     secretName: demo-secret
  #     items:
  #       - key: secret.conf
  #         path: secret.conf #}

terminationGracePeriodSeconds: 30

minReadySeconds: 5

replicas: 1

scaling:
  min: 1
  max: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    # - type: Resource
    #   resource:
    #     name: memory
    #     targetAverageValue: 2500Mi

affinty:
  antiAffinity: "soft"
  nodeAffinity: {}

service:
  type: ClusterIP
  ports:
    - name: fe-export
      port: 4443
      targetPort: fe-nginx
      protocol: TCP
