labels:
  env: prod

appImage:
  config:
    resources:
      requests:
        cpu: 1
        memory: 1.5Gi
      limits:
        cpu: 2
        memory: 3Gi

nginxImage:
  config:
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/prod.conf
        subPath: prod.conf

replicas: 2

scaling:
  min: 2
  max: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    # - type: Resource
    #   resource:
    #     name: memory
    #     targetAverageValue: 2500Mi
